modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="trade_platform" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Datapack Loottable Maker" #mandatory
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gloomy_banana" #optional
description='''

'''
